SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE pet_type (
  pet_type_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO pet_type (pet_type_id,name) VALUES
(1, 'Dog (Canine)'),
(2, 'Cat (Feline)'),
(3, 'Other');

CREATE TABLE pet_breed (
  pet_breed_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pet_type_id INTEGER UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  FOREIGN KEY (pet_type_id) REFERENCES pet_type(pet_type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO pet_breed (pet_breed_id,pet_type_id,name,image) VALUES
(1, 1, 'Mixed / Unknown', 'unknown.png'),
(2, 1, 'Affenpinscher', 'affenpinscher'),
(3, 1, 'Afghan Hound', 'afghan_hound'),
(4, 1, 'Airedale Terrier', 'airedale_terrier'),
(5, 1, 'Akita', 'akita'),
(6, 1, 'Alaskan Malamute', 'alaskan_malamute'),
(7, 1, 'American English Coonhound', 'american_english_coonhound'),
(8, 1, 'American Eskimo Dog', 'american_eskimo_dog'),
(9, 1, 'American Foxhound', 'american_foxhound'),
(10, 1, 'American Staffordshire Terrier', 'american_staffordshire_terrier'),
(11, 1, 'American Water Spaniel', 'american_water_spaniel'),
(12, 1, 'Anatolian Shepherd Dog', 'anatolian_shepherd_dog'),
(13, 1, 'Australian Cattle Dog', 'australian_cattle_dog'),
(14, 1, 'Australian Shepherd', 'australian_shepherd'),
(15, 1, 'Australian Terrier', 'australian_terrier'),
(16, 1, 'Basenji', 'basenji'),
(17, 1, 'Basset Hound', 'basset_hound'),
(18, 1, 'Beagle', 'beagle'),
(19, 1, 'Bearded Collie', 'bearded_collie'),
(20, 1, 'Beauceron', 'beauceron'),
(21, 1, 'Bedlington Terrier', 'bedlington_terrier'),
(22, 1, 'Belgian Malinois', 'belgian_malinois'),
(23, 1, 'Belgian Sheepdog', 'belgian_sheepdog'),
(24, 1, 'Belgian Tervuren', 'belgian_tervuren'),
(25, 1, 'Bernese Mountain Dog', 'bernese_mountain_dog'),
(26, 1, 'Bichon Frise', 'bichon_frise'),
(27, 1, 'Black and Tan Coonhound', 'black_tan_coonhound'),
(28, 1, 'Black Russian Terrier', 'black_russian_terrier'),
(29, 1, 'Bloodhound', 'bloodhound'),
(30, 1, 'Bluetick Coonhound', 'bluetick_coonhound'),
(31, 1, 'Border Collie', 'border_collie'),
(32, 1, 'Border Terrier', 'border_terrier'),
(33, 1, 'Borzoi', 'borzoi'),
(34, 1, 'Boston Terrier', 'boston_terrier'),
(35, 1, 'Bouvier des Flandres', 'bouvier_des_flandres'),
(36, 1, 'Boxer', 'boxer'),
(37, 1, 'Boykin Spaniel', 'boykin_spaniel'),
(38, 1, 'Briard', 'briard'),
(39, 1, 'Brittany', 'brittany'),
(40, 1, 'Brussels Griffon', 'brussels_griffon'),
(41, 1, 'Bull Terrier', 'bull_terrier'),
(42, 1, 'Bulldog', 'bulldog'),
(43, 1, 'Bullmastiff', 'bullmastiff'),
(44, 1, 'Cairn Terrier', 'cairn_terrier'),
(45, 1, 'Canaan Dog', 'canaan_dog'),
(46, 1, 'Cane Corso', 'cane_corso'),
(47, 1, 'Cardigan Welsh Corgi', 'cardigan_welsh_corgi'),
(48, 1, 'Cavalier King Charles Spaniel', 'cavalier_king_charles_spaniel'),
(49, 1, 'Cesky Terrier', 'cesky_terrier'),
(50, 1, 'Chesapeake Bay Retriever', 'chesapeake_bay_retriever'),
(51, 1, 'Chihuahua', 'chihuahua'),
(52, 1, 'Chinese Crested', 'chinese_crested'),
(53, 1, 'Chinese Shar-Pei', 'chinese_shar_pei'),
(54, 1, 'Chow Chow', 'chow_chow'),
(55, 1, 'Clumber Spaniel', 'clumber_spaniel'),
(56, 1, 'Cocker Spaniel', 'cocker_spaniel'),
(57, 1, 'Collie', 'collie'),
(58, 1, 'Curly-Coated Retriever', 'curly_coated_retriever'),
(59, 1, 'Dachshund', 'dachshund'),
(60, 1, 'Dalmatian', 'dalmatian'),
(61, 1, 'Dandie Dinmont Terrier', 'dandie_dinmont_terrier'),
(62, 1, 'Doberman Pinscher', 'doberman_pinscher'),
(63, 1, 'Dogue de Bordeaux', 'dogue_de_bordeaux'),
(64, 1, 'English Cocker Spaniel', 'english_cocker_spaniel'),
(65, 1, 'English Foxhound', 'english_foxhound'),
(66, 1, 'English Setter', 'english_setter'),
(67, 1, 'English Springer Spaniel', 'english_springer_spaniel'),
(68, 1, 'English Toy Spaniel', 'english_toy_spaniel'),
(69, 1, 'Entlebucher Mountain Dog', 'entlebucher_mountain_dog'),
(70, 1, 'Field Spaniel', 'field_spaniel'),
(71, 1, 'Finnish Lapphund', 'finnish_lapphund'),
(72, 1, 'Finnish Spitz', 'finnish_spitz'),
(73, 1, 'Flat-Coated Retriever', 'flat_coated_retriever'),
(74, 1, 'French Bulldog', 'french_bulldog'),
(75, 1, 'German Pinscher', 'german_pinscher'),
(76, 1, 'German Shepherd Dog', 'german_shepherd_dog'),
(77, 1, 'German Shorthaired Pointer', 'german_shorthaired_pointer'),
(78, 1, 'German Wirehaired Pointer', 'german_wirehaired_pointer'),
(79, 1, 'Giant Schnauzer', 'giant_schnauzer'),
(80, 1, 'Glen of Imaal Terrier', 'glen_of_imaal_terrier'),
(81, 1, 'Golden Retriever', 'golden_retriever'),
(82, 1, 'Gordon Setter', 'gordon_setter'),
(83, 1, 'Great Dane', 'great_dane'),
(84, 1, 'Great Pyrenees', 'great_pyrenees'),
(85, 1, 'Greater Swiss Mountain Dog', 'greater_swiss_mountain_dog'),
(86, 1, 'Greyhound', 'greyhound'),
(87, 1, 'Harrier', 'harrier'),
(88, 1, 'Havanese', 'havanese'),
(89, 1, 'Ibizan Hound', 'ibizan_hound'),
(90, 1, 'Icelandic Sheepdog', 'icelandic_sheepdog'),
(91, 1, 'Irish Red and White Setter', 'irish_red_white_setter'),
(92, 1, 'Irish Setter', 'irish_setter'),
(93, 1, 'Irish Terrier', 'irish_terrier'),
(94, 1, 'Irish Water Spaniel', 'irish_water_spaniel'),
(95, 1, 'Irish Wolfhound', 'irish_wolfhound'),
(96, 1, 'Italian Greyhound', 'italian_greyhound'),
(97, 1, 'Japanese Chin', 'japanese_chin'),
(98, 1, 'Keeshond', 'keeshond'),
(99, 1, 'Kerry Blue Terrier', 'kerry_blue_terrier'),
(100, 1, 'Komondor', 'komondor'),
(101, 1, 'Kuvasz', 'kuvasz'),
(102, 1, 'Labrador Retriever', 'labrador_retriever'),
(103, 1, 'Lakeland Terrier', 'lakeland_terrier'),
(104, 1, 'Leonberger', 'leonberger'),
(105, 1, 'Lhasa Apso', 'lhasa_apso'),
(106, 1, 'Löwchen', 'lowchen'),
(107, 1, 'Maltese', 'maltese'),
(108, 1, 'Manchester Terrier', 'manchester_terrier'),
(109, 1, 'Mastiff', 'mastiff'),
(110, 1, 'Miniature Bull Terrier', 'miniature_bull_terrier'),
(111, 1, 'Miniature Pinscher', 'miniature_pinscher'),
(112, 1, 'Miniature Schnauzer', 'miniature_schnauzer'),
(113, 1, 'Neapolitan Mastiff', 'neapolitan_mastiff'),
(114, 1, 'Newfoundland', 'newfoundland'),
(115, 1, 'Norfolk Terrier', 'norfolk_terrier'),
(116, 1, 'Norwegian Buhund', 'norwegian_buhund'),
(117, 1, 'Norwegian Elkhound', 'norwegian_elkhound'),
(118, 1, 'Norwegian Lundehund', 'norwegian_lundehund'),
(119, 1, 'Norwich Terrier', 'norwich_terrier'),
(120, 1, 'Nova Scotia Duck Tolling Retriever', 'nova_scotia_duck_tolling_retriever'),
(121, 1, 'Old English Sheepdog', 'old_english_sheepdog'),
(122, 1, 'Otterhound', 'otterhound'),
(123, 1, 'Papillon', 'papillon'),
(124, 1, 'Parson Russell Terrier', 'parson_russell_terrier'),
(125, 1, 'Pekingese', 'pekingese'),
(126, 1, 'Pembroke Welsh Corgi', 'pembroke_welsh_corgi'),
(127, 1, 'Petit Basset Griffon Vendéen', 'petit_basset_griffon_vendeen'),
(128, 1, 'Pharaoh Hound', 'pharaoh_hound'),
(129, 1, 'Plott', 'plott'),
(130, 1, 'Pointer', 'pointer'),
(131, 1, 'Polish Lowland Sheepdog', 'polish_lowland_sheepdog'),
(132, 1, 'Pomeranian', 'pomeranian'),
(133, 1, 'Poodle', 'poodle'),
(134, 1, 'Portuguese Water Dog', 'portuguese_water_dog'),
(135, 1, 'Pug', 'pug'),
(136, 1, 'Puli', 'puli'),
(137, 1, 'Pyrenean Shepherd', 'pyrenean_shepherd'),
(138, 1, 'Redbone Coonhound', 'redbone_coonhound'),
(139, 1, 'Rhodesian Ridgeback', 'rhodesian_ridgeback'),
(140, 1, 'Rottweiler', 'rottweiler'),
(141, 1, 'Saint Bernard', 'saint_bernard'),
(142, 1, 'Saluki', 'saluki'),
(143, 1, 'Samoyed', 'samoyed'),
(144, 1, 'Schipperke', 'schipperke'),
(145, 1, 'Scottish Deerhound', 'scottish_deerhound'),
(146, 1, 'Scottish Terrier', 'scottish_terrier'),
(147, 1, 'Sealyham Terrier', 'sealyham_terrier'),
(148, 1, 'Shetland Sheepdog', 'shetland_sheepdog'),
(149, 1, 'Shiba Inu', 'shiba_inu'),
(150, 1, 'Shih Tzu', 'shih_tzu'),
(151, 1, 'Siberian Husky', 'siberian_husky'),
(152, 1, 'Silky Terrier', 'silky_terrier'),
(153, 1, 'Skye Terrier', 'skye_terrier'),
(154, 1, 'Smooth Fox Terrier', 'smooth_fox_terrier'),
(155, 1, 'Soft Coated Wheaten Terrier', 'soft_coated_wheaten_terrier'),
(156, 1, 'Spinone Italiano', 'spinone_italiano'),
(157, 1, 'Staffordshire Bull Terrier', 'staffordshire_bull_terrier'),
(158, 1, 'Standard Schnauzer', 'standard_schnauzer'),
(159, 1, 'Sussex Spaniel', 'sussex_spaniel'),
(160, 1, 'Swedish Vallhund', 'swedish_vallhund'),
(161, 1, 'Tibetan Mastiff', 'tibetan_mastiff'),
(162, 1, 'Tibetan Spaniel', 'tibetan_spaniel'),
(163, 1, 'Tibetan Terrier', 'tibetan_terrier'),
(164, 1, 'Toy Fox Terrier', 'toy_fox_terrier'),
(165, 1, 'Vizsla', 'vizsla'),
(166, 1, 'Weimaraner', 'weimaraner'),
(167, 1, 'Welsh Springer Spaniel', 'welsh_springer_spaniel'),
(168, 1, 'Welsh Terrier', 'welsh_terrier'),
(169, 1, 'West Highland White Terrier', 'west_highland_white_terrier'),
(170, 1, 'Whippet', 'whippet'),
(171, 1, 'Wire Fox Terrier', 'wire_fox_terrier'),
(172, 1, 'Wirehaired Pointing Griffon', 'wirehaired_pointing_griffon'),
(173, 1, 'Xoloitzcuintli', 'xoloitzcuintli'),
(174, 1, 'Yorkshire Terrier', 'yorkshire_terrier'),
(175, 1, 'Azawakh', 'azawakh'),
(176, 1, 'Belgian Laekenois', 'belgian_laekenois'),
(177, 1, 'Bergamasco', 'bergamasco'),
(178, 1, 'Boerboel', 'south_african_boerboel'),
(179, 1, 'Chinook', 'chinook'),
(180, 1, 'Dogo Argentino', 'argentine_dogo'),
(181, 1, 'Peruvian Inca Orchid', 'peruvian_inca_orchid'),
(182, 1, 'Portuguese Podengo Pequeno', 'portuguese_podengo_pequeno'),
(183, 1, 'Pumi', 'pumi'),
(184, 1, 'Rat Terrier', 'rat_terrier'),
(185, 1, 'Russell Terrier', 'russell_terrier'),
(186, 1, 'Sloughi', 'sloughi'),
(187, 1, 'Treeing Walker Coonhound', 'treeing_walker_coonhound'),
(188, 1, 'Wirehaired Vizsla', 'wirehaired_vizsla'),
(189, 1, 'Appenzeller Sennenhunde', 'appenzeller_sennenhunde'),
(190, 1, 'Barbet', 'barbet'),
(191, 1, 'Bergamasco', 'berger_picard'),
(192, 1, 'Bolognese', 'bolognese'),
(193, 1, 'Bracco Italiano', 'bracco_italiano'),
(194, 1, 'Catahoula Leopard Dog', 'catahoula_leopard_dog'),
(195, 1, 'Caucasian Ovcharka', 'caucasian_mountain_dog'),
(196, 1, 'Central Asian Shepherd', 'central_asian_shepherd_dog'),
(197, 1, 'Cirneco dell\'Etna', 'cirneco_dell_etna'),
(198, 1, 'Coton de Tulear', 'coton_de_tulear'),
(199, 1, 'Czechoslovakian Vlcak', 'czechoslovakian_wolfdog'),
(200, 1, 'Danish-Swedish Farmdog', 'danish-swedish_farmdog'),
(201, 1, 'Drentsche Patrijshond', 'drentsche_patrijshond'),
(202, 1, 'Estrela Mountain Dog', 'estrela_mountain_dog'),
(203, 1, 'Eurasier', 'eurasier'),
(204, 1, 'German Longhaired Pointer', 'german_longhaired_pointer'),
(205, 1, 'German Spitz', 'german_spitz'),
(206, 1, 'Grand Basset Griffon Vendéen', 'grand_basset_griffon_vendeen'),
(207, 1, 'Hamiltonstövare', 'hamiltonstovare'),
(208, 1, 'Hovawart', 'hovawart'),
(209, 1, 'Jindo', 'jindo'),
(210, 1, 'Kai Ken', 'kai_ken'),
(211, 1, 'Karelian Bear Dog', 'karelian_bear_dog'),
(212, 1, 'Kishu Ken', 'kishu_ken'),
(213, 1, 'Kooikerhondje', 'kooikerhondje'),
(214, 1, 'Lagotto Romagnolo', 'lagotto_romagnolo'),
(215, 1, 'Lancashire Heeler', 'lancashire_heeler'),
(216, 1, 'Miniature American Shepherd', 'miniature_american_shepherd'),
(217, 1, 'Mudi', 'mudi'),
(218, 1, 'Norrbottenspets', 'norrbottenspets'),
(219, 1, 'Perro de Presa Canario', 'perro_de_presa_canario'),
(220, 1, 'Portuguese Podengo', 'portuguese_podengo'),
(221, 1, 'Portuguese Pointer', 'portuguese_pointer'),
(222, 1, 'Rafeiro do Alentejo', 'rafeiro_do_alentejo'),
(223, 1, 'Russian Toy', 'russian_toy'),
(224, 1, 'Schapendoes', 'schapendoes'),
(225, 1, 'Slovensky Cuvac', 'slovensky_cuvac'),
(226, 1, 'Small Munsterlander Pointer', 'small_munsterlander_pointer'),
(227, 1, 'Spanish Mastiff', 'spanish_mastiff'),
(228, 1, 'Spanish Water Dog', 'spanish_water_dog'),
(229, 1, 'Stabyhoun', 'stabyhoun'),
(230, 1, 'Swedish Lapphund', 'swedish_lapphund'),
(231, 1, 'Thai Ridgeback', 'thai_ridgeback'),
(232, 1, 'Tosa', 'tosa'),
(233, 1, 'Treeing Tennessee Brindle', 'treeing_tennessee_brindle');

CREATE TABLE pet (
  pet_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  gender ENUM('unspecified','male', 'female') NOT NULL DEFAULT 'unspecified',
  birthday DATETIME DEFAULT NULL,
  pet_breed_id INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY (pet_breed_id) REFERENCES pet_breed(pet_breed_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user (
  user_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  language VARCHAR(255) DEFAULT NULL,
  last_login DATETIME DEFAULT NULL,
  last_ip INTEGER DEFAULT NULL,
  register_time DATETIME NOT NULL,
  register_ip INTEGER NOT NULL,
  UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE hybrid_auth (
  user_id INTEGER UNSIGNED NOT NULL,
  authentication_type ENUM('google','facebook', 'openid') NOT NULL DEFAULT 'google',
  uid VARCHAR(255) NOT NULL,
  provider_uid VARCHAR(255) NOT NULL,
  timestamp DATETIME DEFAULT NULL,
  PRIMARY KEY (user_id,authentication_type),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE pet_owner (
  pet_id INTEGER UNSIGNED NOT NULL,
  user_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (pet_id,user_id),
  FOREIGN KEY (pet_id) REFERENCES pet(pet_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_settings (
  user_id INTEGER UNSIGNED NOT NULL,
  name VARCHAR(50) NOT NULL,
  value VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (user_id,name),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_role (
  role_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  weight INTEGER NOT NULL DEFAULT '0',
  KEY weight (weight)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=4;

INSERT INTO user_role (role_id,name,weight) VALUES
(1, 'guest', 0),
(2, 'admin', 99),
(3, 'user',  10);

CREATE TABLE user_role_linker (
  user_id INTEGER UNSIGNED NOT NULL,
  role_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (user_id,role_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (role_id) REFERENCES user_role(role_id)
) ENGINE=InnoDB;

CREATE TABLE acl_record (
  role_id INTEGER UNSIGNED NOT NULL,
  resource VARCHAR(255) DEFAULT NULL,
  action VARCHAR(255) DEFAULT NULL,
  type ENUM('allow','deny') NOT NULL DEFAULT 'allow',
  UNIQUE KEY role_resource_action (role_id,resource,action),
  FOREIGN KEY (role_id) REFERENCES user_role(role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE acl_resource_record (
  role_id INTEGER UNSIGNED NOT NULL,
  resource_type VARCHAR(255) NOT NULL,
  resource_id INTEGER unsigned NOT NULL,
  PRIMARY KEY (role_id,resource_type,resource_id),
  FOREIGN KEY (role_id) REFERENCES user_role(role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE label (
  label_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  text VARCHAR(50) NOT NULL,
  color VARCHAR(50) NOT NULL,
  private BOOLEAN NOT NULL DEFAULT '0'
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

